artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/Ramakrishna-Cheriala/DS-project/raw/main/Chicken-fecal-images.zip
  local_dir_files: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
